{% set name = "hep_ml" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1729a13ef4c7187b05cd3723091f804ecba435f886567bd963a719ae108689b8
  patches:
    - 0001-Remove-theano-from-deps.patch

build:
  number: 1
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - numpy >=1.9
    - pandas >=0.14.0
    - python >={{ python_min }}
    - scikit-learn >=0.19
    - scipy >=0.15.0
    - six

test:
  requires:
    - python {{ python_min }}
  imports:
    - hep_ml
    - hep_ml.experiments

about:
  home: https://github.com/arogozhnikov/hep_ml
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Machine Learning for High Energy Physics
  doc_url: https://github.com/arogozhnikov/hep_ml
  dev_url: https://github.com/arogozhnikov/hep_ml

extra:
  recipe-maintainers:
    - chrisburr
